#! /usr/bin/env bash
# -*- mode: sh -*-
set -uvx
set -e
cd "$(dirname "$0")"
cwd=$(pwd)
ts=$(date "+%Y.%m%d.%H%M.%S")

echo "#! /usr/bin/env open-markdown">tmp.++playlist.md
tail -n 10 ++playlist.md>>tmp.++playlist.md
mv tmp.++playlist.md ++playlist.md
