#! /usr/bin/env bash
set -uvx
set -e
cd "$(dirname "$0")"
cwd=$(pwd)
ts=$(date "+%Y.%m%d.%H%M.%S")

killall.exe bluegriffon.exe || true

random-m4a.exe
random-m4a.exe
random-m4a.exe
random-m4a.exe
random-m4a.exe

cp index.template.html index.html
./html-filter.exe list.html|tac>> index.html

firefox index.html
