#! /usr/bin/env bash
set -uvx
set -e
cd "$(dirname "$0")"
cwd=$(pwd)
ts=$(date "+%Y.%m%d.%H%M.%S")

random-m4a.exe
random-m4a.exe
random-m4a.exe
random-m4a.exe
random-m4a.exe

cp index.template.html index.html
tac list.html>>index.html

firefox index.html
