#! /usr/bin/env bash
set -uvx
set -e
cd "$(dirname "$0")"
cwd=$(pwd)
ts=$(date "+%Y.%m%d.%H%M.%S")

killall.exe bluegriffon.exe || true

for ((i = 0; i < 500; ++i)); do
    echo "Counter is: $i"
    random-m4a.exe || true
done

cp index.template.html index.html
./html-filter.exe @@playlist.md|tac>> index.html

firefox index.html
